### ISSUE TITLE
Can novels be downloaded?

### ISSUE THREAD

**Issue by Xeiv** [TilCreator/Tapas-Comic-Downloader#10]
Does it only download comics or can it download novels too?

**Comment by TilCreator** [comment]
Currently it only downloads comics, didn't know that tapas has novels, too.

I think it should be easy to modify the script to download novels as well, I just have not much time right now.
Could you provide an example?

**Comment by Xeiv** [comment]
They're here https://tapas.io/novels and example would be https://tapas.io/series/TBATE

Idk if this helps:
All the pages have the class episode and the id episode-[numbers here]
eg: for the novel I sent the id of the first page is episode-571162

**Comment by TilCreator** [comment]
Added in 8ffc7e5fef94d71d47594e7c5dda7eb0fb8b689f
Could you plz test?

**Comment by TilCreator** [comment]
Solved
