### ISSUE TITLE
dataStr error

### ISSUE THREAD

**Issue by Asmodeus6969** [TilCreator/Tapas-Comic-Downloader#15]
Not an expert in python at all, but this happens. I followed the instructions, did I miss something?

`root@porn-bot ~/tapas# python3 tapas-dl.py https://tapas.io/series/Erma
Traceback (most recent call last):
  File "tapas-dl.py", line 77, in <module>
    dataStr = [dataStr for dataStr in page('script') if dataStr.text is not None and dataStr.text.find('var _data = {') != -1][0].text.replace('\n', '')
IndexError: list index out of range
`

**Comment by TilCreator** [comment]
See #14 
Closing this because is a dublicate.
