### ISSUE TITLE
[Windows] Issue while detecting if it's Novel (Solved)

### ISSUE THREAD

**Issue by Syntist** [TilCreator/Tapas-Comic-Downloader#16]
I just tried it out, did follow all the steps 
but can't get it to work
Issue I am facing is on Line No 148-149 
Basically it's saying IndexError

![image](https://user-images.githubusercontent.com/24858150/77253214-aea3c600-6c7a-11ea-9b75-86b3804748a7.png)

**Comment by TilCreator** [comment]
Try again plz

**Comment by Syntist** [comment]
Thanks It's Working now.

**Comment by Efreak** [comment]
This is broken again. I'm guessing Tapas changed their site. It's unfortunate, because this is the only thing I've seen that claims ability to scrape tapas novels.

Edit: I should mention it's broken on both novels and comics

**Comment by TilCreator** [comment]
I will have a look at it tomorrow (Wish I had someone else helping (opening issues is also helping, but still more work for me ^^))

I will not reopen this issue, because it's probably directly related to #23
