### ISSUE TITLE
slight difficulty 

### ISSUE THREAD

**Issue by Holydragoness** [TilCreator/Tapas-Comic-Downloader#24]
Well, I am having great difficulty with the coding in general as I do have python but let's just say for some reason it too difficult for me to use is there a way which it can be simplified for can you just turn this into the software which does it for you? 
Even though you can't can you at least send me the software needed the website is way too confusing for me to use

**Comment by TilCreator** [comment]
Do you mean like #30?
Can I close this then?

**Comment by Holydragoness** [comment]
Its more of can you like make the process simpler as using the program which you use is too difficult for me

**Comment by TilCreator** [comment]
I can do that, but it would be time intensive for me and I really don't need it (this is actually one of the simplest ways for me to use this downloader).
I opened an issue #30 that describes how I would handle making the program simpler to use (for Win users), but I will probably never work on that (Instead would welcome anyone who would).
So I'm closing this now, feel free to open the issue again if you have further questions.
