### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by Wolfhoodie** [TilCreator/Tapas-Comic-Downloader#25]
Hello I'm new to github and didn't see where to make a normal comment. But i wanted to ask does this work for downloading novels from the site too? Not just comics also I'm new to Python and wanted to ask how i would install the models. Thank you and sorry about this 😅

**Comment by TilCreator** [comment]
1. You can only write "purpose driven" comments here, so issues or pull requests, not much else.
2. Yes this works for novel too, it's written in the [README.md](https://github.com/TilCreator/Tapas-Comic-Downloader/blob/master/README.md) (not very clearly, but you should have spotted it, if you had read it.)
3. What do you mean with "models"? How to install and how to use is written down in the [README.md](https://github.com/TilCreator/Tapas-Comic-Downloader/blob/master/README.md).

**Comment by Wolfhoodie** [comment]
Sorry i read it but only really spotted the comic part thank you! And i see so there's no comment section thank you,and I'll read the how to Install again i never really used Python. 🙇thank you for answering!
