### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by TikkiToxin** [TilCreator/Tapas-Comic-Downloader#26]
I was trying to update a comic, and it gave me this error.

Traceback (most recent call last):
  File "tapas-dl.py", line 138, in <module>
    if True not in [file.starts_with('-1 - header.') for file in os.scandir(savePath)]:
  File "tapas-dl.py", line 138, in <listcomp>
    if True not in [file.starts_with('-1 - header.') for file in os.scandir(savePath)]:
AttributeError: 'posix.DirEntry' object has no attribute 'starts_with'

I'm not super familiar with python, so I'm not sure what I should do to fix it. Any help would be appreciated.

**Comment by TilCreator** [comment]
Fixed
