### ISSUE TITLE
Tapas novel download

### ISSUE THREAD

**Issue by Arleng001** [TilCreator/Tapas-Comic-Downloader#28]
Will this work when downloading novels in tapas?

**Comment by TilCreator** [comment]
Jup, as described in the [README.md](https://github.com/TilCreator/Tapas-Comic-Downloader/blob/master/README.md)

**Comment by Arleng001** [comment]
Even the  novels that need to be unlocked/paid?

**Comment by TilCreator** [comment]
No, how would I do that?
