### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by etcetera04** [TilCreator/Tapas-Comic-Downloader#29]
I'm trying to download a novel, but it just keeps showing this (I blacked out my username). I downloaded the requirements correctly, and I have python installed correctly too, so I don't know what the problem is.
![Capture Edited](https://user-images.githubusercontent.com/73797759/97814768-b24ef080-1c3e-11eb-86d6-ef7e0a9ddbef.png)

**Comment by TilCreator** [comment]
You have to use Python 3
(Python 2 is end of life since almost a year now anyway)

**Comment by etcetera04** [comment]
Okay, I just downloaded the latest version of python and I'll try again.

**Comment by Duhhmas** [comment]
Now this happened. I made sure that python was downloaded in PATH.

![tempsnip](https://user-images.githubusercontent.com/73797759/97815119-d14e8200-1c40-11eb-94f0-ac623153bb52.png)

**Comment by etcetera04** [comment]
Now this happened. I made sure that Python was downloaded in PATH.

![tempsnip](https://user-images.githubusercontent.com/73797759/97815154-0529a780-1c41-11eb-94e8-6255d089fc88.png)

**Comment by TilCreator** [comment]
Just follow the README.md and istall the dependencies first.

**Comment by etcetera04** [comment]
Thanks! I downloaded the requirements again, and it worked.
