### ISSUE TITLE
OT: Want to publish a mayor rewrite of your old php downloader.

### ISSUE THREAD

**Issue by l1m3r** [TilCreator/Tapas-Comic-Downloader#5]
Hi @TilCreator,

I finally did a major rewrite of your old "tapas.io_downloader.php" and want to know how I should credit you and so on.... (see collaboration invite)

and since I don't know a better way to contact you I opened an issue instead :-/

**Comment by TilCreator** [comment]
I would be thankful but it is not necessary.
I will probably also soon credit you in my README, since you did some character filtering that I am missing (and will probably copy). (#6)

**Comment by l1m3r** [comment]
Ok. But I didn't want to know _if_ but _how_ I should credit you. See if you're okay with how I did it now.

and my character filtering is not a 100% tested.

**Comment by TilCreator** [comment]
Ups, sorry :upside_down_face:.
Just put a link to this repository somewhere in your README.

**Comment by TilCreator** [comment]
Sorry for bumping
But you got a thing in your readme wrong:
It's Python (not Perl) alternative. ^^

**Comment by l1m3r** [comment]
NP. Fixed - dunno how I got that mixed up.
