### ISSUE TITLE
argument error

### ISSUE THREAD

**Issue by swordfishvirus** [TilCreator/Tapas-Comic-Downloader#7]
" tapas.dl: error: the following arguments are required: url/name

**Comment by TilCreator** [comment]
Please be much **more** specific, I have no idea what you are trying to do and so on.

**Comment by TilCreator** [comment]
Still alive?

**Comment by swordfishvirus** [comment]
Being busy.. also about the downloader I was getting argument error on line 5 while compiling code.. working on other projects now so haven’t tried to find a solution..

**Comment by TilCreator** [comment]
Have you tried `--help`, to see what the command needs as arguments?

**Comment by TilCreator** [comment]
Is this issue still active?

**Comment by swordfishvirus** [comment]
Yeah.. at this point looking into alternative solution

**Comment by TilCreator** [comment]
OK, closing this then

**Comment by swordfishvirus** [comment]
Have you look into that error
