### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by Delta-473** [TilCreator/Tapas-Comic-Downloader#8]
I have successfully downloaded comics before but following 2 comics give the same error: 
[https://tapas.io/series/Golden-Gunner](url) and [https://tapas.io/series/Sniper-Girl](url)
I'm running the script on Ubuntu on Windows with WSL.

` Loading Sniper-Girl...

Sniper Girl [Sniper-Girl] (5 pages):
 Checking folder...
 Downloading header...
Traceback (most recent call last):
  File "./tapas-dl.py", line 99, in <module>
    headerSrc = re.search(r'url\(".+"\)', customCssStr).group(0)[5:-2]
  File "/usr/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object`

**Comment by Delta-473** [comment]
sorry for bumping *bump*

**Comment by TilCreator** [comment]
Sry for overlooking your issue.
Just had a short look, the error occurs, because the comic has no header image.
Will be fixed in a few minutes.

**Comment by TilCreator** [comment]
Fixed ( 1d6cb8fd1ec43ff7061b1b666170b7f803cb32f5 )
