### ISSUE TITLE
.py just flashes

### ISSUE THREAD

**Issue by NovaMaiden** [TilCreator/Tapas-Comic-Downloader#9]
I never used python before. I doubled click it but just flashes. Not sure what I did wrong.

**Comment by TilCreator** [comment]
Please see the Useage section of the readme

**Comment by NovaMaiden** [comment]
I read it still don't understand it. If I use that I just get invalid syntax.

**Comment by TilCreator** [comment]
You have to execute the script in the terminal (It is a text only tool).
If you put ` --help` after the command (`python tapas-dl.py --help`) you will get an explanation of the tool.

**Comment by TilCreator** [comment]
Is this issue still active?

**Comment by TilCreator** [comment]
Closed because of inactivity
